# Generated by Django 2.1.2 on 2018-10-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=200)),
                ('note_body', models.TextField()),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_saved', models.DateField(auto_now=True)),
            ],
        ),
    ]
