# Generated by Django 2.1.2 on 2018-10-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(default='Quote', max_length=100),
            preserve_default=False,
        ),
    ]
