# Generated by Django 2.1.2 on 2018-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='technology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
