# Generated by Django 2.1.2 on 2018-10-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20181002_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Experience'},
        ),
    ]
