# Generated by Django 2.1.2 on 2018-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20181007_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsection',
            name='date_saved',
            field=models.DateField(auto_now=True),
        ),
    ]
